tw-graceful-shutdown.enable: false

# All values come from .circleci/config.yml
ENV_ROLLBAR_ACCESS_TOKEN: null
ENV_ROLLBAR_ACCESS_ENVIRONMENT: development
ENV_MARIA_SERVICEDB_URL: jdbc:mariadb://maria:3306/circle-realitycheck?useMysqlMetadata=true
ENV_MARIA_SERVICEDB_USERNAME: test
ENV_MARIA_SERVICEDB_PASSWORD: test
ENV_MARIA_SERVICEDB_FLYWAY_USERNAME: root
ENV_MARIA_SERVICEDB_FLYWAY_PASSWORD: admin
ENV_POSTGRES_SERVICEDB_URL: jdbc:postgresql://postgres:5432/circle-realitycheck
ENV_POSTGRES_SERVICEDB_USERNAME: test
ENV_POSTGRES_SERVICEDB_PASSWORD: test
ENV_POSTGRES_SERVICEDB_FLYWAY_USERNAME: test
ENV_POSTGRES_SERVICEDB_FLYWAY_PASSWORD: test
ENV_ROLLBAR_NOTIFY_ABOUT_DEPLOYMENT: false
ENV_TW_SERVICE_TEMPLATE_URL: http://localhost:12345
ENV_EXTERNAL_CLIENT_TYPE: MOCK
ENV_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
